server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;

    root   /usr/share/nginx/html;
    index  index.html;

    location = /modal {
        return 302 /modal/;
    }

    location /modal/ {
        try_files $uri $uri/index.html =404;
    }

    location / {
        try_files $uri /index.html =404;
    }
}
